os: linux
dist: bionic

services:
  - docker

language: node_js
node_js:
  - 'node'
  - 'lts/*'

cache:
  npm: true

install:
  - npm install
  - docker-compose up --detach
  - docker-compose ps

script:
  - npm run compile
  - npm run lint
