version: '3'

services:
  eth:
    image: trufflesuite/ganache-cli
    command: --mnemonic dev
    ports:
      - '8545:8545'

  ipfs:
    image: ipfs/go-ipfs
    command: daemon --init --offline
    ports:
      - '5001:5001'

