version: '3'

services:
  eth:
    image: ethereum/client-go
    command: --dev --http --http.addr 0.0.0.0
    ports:
      - '8545:8545'

  ipfs:
    image: ipfs/go-ipfs
    command: daemon --init --offline
    ports:
      - '5001:5001'

